import type { ComponentRegistry } from '../types'

export const COMPONENTS: ComponentRegistry = {
    // Form Controls
    button: {
        name: 'Button',
        category: 'form',
        dependencies: ['class-variance-authority', 'clsx', 'tailwind-merge', '@radix-ui/react-slot'],
        files: ['button.tsx'],
        description: 'Clickable button with multiple variants and sizes',
        tags: ['form', 'interactive', 'button'],
    },
    input: {
        name: 'Input',
        category: 'form',
        dependencies: ['clsx', 'tailwind-merge'],
        files: ['input.tsx'],
        description: 'Text input field with validation support',
        tags: ['form', 'input', 'text'],
    },
    textarea: {
        name: 'Textarea',
        category: 'form',
        dependencies: ['clsx', 'tailwind-merge'],
        files: ['textarea.tsx'],
        description: 'Multi-line text input field',
        tags: ['form', 'input', 'textarea'],
    },
    checkbox: {
        name: 'Checkbox',
        category: 'form',
        dependencies: ['@radix-ui/react-checkbox', 'lucide-react'],
        files: ['checkbox.tsx'],
        description: 'Checkbox selection control',
        tags: ['form', 'checkbox', 'selection'],
    },
    select: {
        name: 'Select',
        category: 'form',
        dependencies: ['@radix-ui/react-select', 'lucide-react'],
        files: ['select.tsx'],
        description: 'Dropdown selection menu',
        tags: ['form', 'select', 'dropdown'],
    },
    switch: {
        name: 'Switch',
        category: 'form',
        dependencies: ['@radix-ui/react-switch'],
        files: ['switch.tsx'],
        description: 'Toggle switch control for boolean values',
        tags: ['form', 'switch', 'toggle'],
    },
    slider: {
        name: 'Slider',
        category: 'form',
        dependencies: ['@radix-ui/react-slider'],
        files: ['slider.tsx'],
        description: 'Range slider input control',
        tags: ['form', 'slider', 'range'],
    },
    'radio-group': {
        name: 'RadioGroup',
        category: 'form',
        dependencies: ['@radix-ui/react-radio-group', 'lucide-react'],
        files: ['radio-group.tsx'],
        description: 'Set of radio buttons for single option selection',
        tags: ['form', 'radio', 'selection'],
    },
    'input-otp': {
        name: 'InputOTP',
        category: 'form',
        dependencies: ['input-otp', 'lucide-react'],
        files: ['input-otp.tsx'],
        description: 'One-time password and verification code input',
        tags: ['form', 'otp', 'pin', 'verification'],
    },
    label: {
        name: 'Label',
        category: 'form',
        dependencies: ['@radix-ui/react-label', 'class-variance-authority'],
        files: ['label.tsx'],
        description: 'Accessible label component for form controls',
        tags: ['form', 'label', 'accessibility'],
    },
    form: {
        name: 'Form',
        category: 'form',
        dependencies: ['@radix-ui/react-label', '@radix-ui/react-slot', 'react-hook-form'],
        files: ['form.tsx'],
        description: 'Form component with validation and state management',
        tags: ['form', 'validation', 'react-hook-form'],
    },

    // Data Display
    card: {
        name: 'Card',
        category: 'data-display',
        dependencies: ['clsx', 'tailwind-merge'],
        files: ['card.tsx'],
        description: 'Container for grouping related content',
        tags: ['layout', 'card', 'container'],
    },
    badge: {
        name: 'Badge',
        category: 'data-display',
        dependencies: ['class-variance-authority'],
        files: ['badge.tsx'],
        description: 'Small status or label indicator',
        tags: ['badge', 'label', 'status'],
    },
    avatar: {
        name: 'Avatar',
        category: 'data-display',
        dependencies: ['@radix-ui/react-avatar'],
        files: ['avatar.tsx'],
        description: 'User avatar with image fallback and initials',
        tags: ['avatar', 'image', 'user'],
    },
    skeleton: {
        name: 'Skeleton',
        category: 'data-display',
        dependencies: ['clsx', 'tailwind-merge'],
        files: ['skeleton.tsx'],
        description: 'Loading placeholder animation',
        tags: ['skeleton', 'loading', 'placeholder'],
    },
    progress: {
        name: 'Progress',
        category: 'data-display',
        dependencies: ['@radix-ui/react-progress'],
        files: ['progress.tsx'],
        description: 'Progress indicator bar',
        tags: ['progress', 'loading', 'status'],
    },
    table: {
        name: 'Table',
        category: 'data-display',
        dependencies: ['clsx', 'tailwind-merge'],
        files: ['table.tsx'],
        description: 'Semantic data table component',
        tags: ['table', 'data', 'grid'],
    },
    separator: {
        name: 'Separator',
        category: 'data-display',
        dependencies: ['@radix-ui/react-separator'],
        files: ['separator.tsx'],
        description: 'Visual divider line between elements',
        tags: ['separator', 'divider', 'layout'],
    },
    chart: {
        name: 'Chart',
        category: 'data-display',
        dependencies: ['recharts'],
        files: ['chart.tsx'],
        description: 'Configurable chart container and tooltip component',
        tags: ['chart', 'analytics', 'recharts'],
    },

    // Feedback
    alert: {
        name: 'Alert',
        category: 'feedback',
        dependencies: ['class-variance-authority'],
        files: ['alert.tsx'],
        description: 'Contextual feedback and alert banners',
        tags: ['alert', 'feedback', 'notification'],
    },
    dialog: {
        name: 'Dialog',
        category: 'feedback',
        dependencies: ['@radix-ui/react-dialog', 'lucide-react'],
        files: ['dialog.tsx'],
        description: 'Modal dialog window',
        tags: ['dialog', 'modal', 'overlay'],
    },
    'alert-dialog': {
        name: 'AlertDialog',
        category: 'feedback',
        dependencies: ['@radix-ui/react-alert-dialog'],
        files: ['alert-dialog.tsx'],
        description: 'Modal dialog for destructive or critical actions',
        tags: ['alert-dialog', 'modal', 'confirmation'],
    },
    toast: {
        name: 'Toast',
        category: 'feedback',
        dependencies: ['@radix-ui/react-toast', 'class-variance-authority', 'lucide-react'],
        files: ['toast.tsx', 'toaster.tsx', 'use-toast.ts'],
        description: 'Toast notifications with dispatch hook',
        tags: ['toast', 'notification', 'alert'],
    },
    sonner: {
        name: 'Sonner',
        category: 'feedback',
        dependencies: ['sonner', 'next-themes'],
        files: ['sonner.tsx'],
        description: 'Opinionated toast notification system',
        tags: ['sonner', 'toast', 'notification'],
    },
    tooltip: {
        name: 'Tooltip',
        category: 'feedback',
        dependencies: ['@radix-ui/react-tooltip'],
        files: ['tooltip.tsx'],
        description: 'Hover/focus tooltip popups',
        tags: ['tooltip', 'hover', 'helper'],
    },
    popover: {
        name: 'Popover',
        category: 'feedback',
        dependencies: ['@radix-ui/react-popover'],
        files: ['popover.tsx'],
        description: 'Floating popover panel triggered by button',
        tags: ['popover', 'floating', 'overlay'],
    },
    'hover-card': {
        name: 'HoverCard',
        category: 'feedback',
        dependencies: ['@radix-ui/react-hover-card'],
        files: ['hover-card.tsx'],
        description: 'Card preview on hover for links and mentions',
        tags: ['hover-card', 'preview', 'card'],
    },

    // Navigation
    tabs: {
        name: 'Tabs',
        category: 'navigation',
        dependencies: ['@radix-ui/react-tabs'],
        files: ['tabs.tsx'],
        description: 'Tabbed interface for organizing views',
        tags: ['tabs', 'navigation', 'layout'],
    },
    accordion: {
        name: 'Accordion',
        category: 'navigation',
        dependencies: ['@radix-ui/react-accordion', 'lucide-react'],
        files: ['accordion.tsx'],
        description: 'Collapsible accordion content panels',
        tags: ['accordion', 'collapse', 'panels'],
    },
    breadcrumb: {
        name: 'Breadcrumb',
        category: 'navigation',
        dependencies: ['@radix-ui/react-slot', 'lucide-react'],
        files: ['breadcrumb.tsx'],
        description: 'Hierarchical navigation trail indicator',
        tags: ['breadcrumb', 'navigation', 'trail'],
    },
    pagination: {
        name: 'Pagination',
        category: 'navigation',
        dependencies: ['lucide-react'],
        files: ['pagination.tsx'],
        description: 'Pagination controls with prev/next buttons',
        tags: ['pagination', 'navigation', 'paging'],
    },
    'navigation-menu': {
        name: 'NavigationMenu',
        category: 'navigation',
        dependencies: ['@radix-ui/react-navigation-menu', 'class-variance-authority', 'lucide-react'],
        files: ['navigation-menu.tsx'],
        description: 'Top-level desktop and responsive navigation menu',
        tags: ['navigation-menu', 'navbar', 'menu'],
    },
    menubar: {
        name: 'Menubar',
        category: 'navigation',
        dependencies: ['@radix-ui/react-menubar', 'lucide-react'],
        files: ['menubar.tsx'],
        description: 'Desktop-style application menubar',
        tags: ['menubar', 'menu', 'desktop'],
    },

    // Overlay & Layout
    sheet: {
        name: 'Sheet',
        category: 'overlay',
        dependencies: ['@radix-ui/react-dialog', 'class-variance-authority', 'lucide-react'],
        files: ['sheet.tsx'],
        description: 'Slide-out drawer panel from screen edge',
        tags: ['sheet', 'drawer', 'sidebar', 'panel'],
    },
    drawer: {
        name: 'Drawer',
        category: 'overlay',
        dependencies: ['vaul'],
        files: ['drawer.tsx'],
        description: 'Mobile-friendly bottom drawer component',
        tags: ['drawer', 'vaul', 'mobile', 'overlay'],
    },
    sidebar: {
        name: 'Sidebar',
        category: 'layout',
        dependencies: ['@radix-ui/react-slot', 'class-variance-authority', 'lucide-react'],
        files: ['sidebar.tsx'],
        description: 'Full-featured collapsible sidebar layout system',
        tags: ['sidebar', 'layout', 'navigation'],
    },
    command: {
        name: 'Command',
        category: 'overlay',
        dependencies: ['cmdk', '@radix-ui/react-dialog', 'lucide-react'],
        files: ['command.tsx'],
        description: 'Fast, composable command palette / search menu',
        tags: ['command', 'cmdk', 'palette', 'search'],
    },
    'context-menu': {
        name: 'ContextMenu',
        category: 'overlay',
        dependencies: ['@radix-ui/react-context-menu', 'lucide-react'],
        files: ['context-menu.tsx'],
        description: 'Right-click context menu',
        tags: ['context-menu', 'right-click', 'menu'],
    },
    'dropdown-menu': {
        name: 'DropdownMenu',
        category: 'overlay',
        dependencies: ['@radix-ui/react-dropdown-menu', 'lucide-react'],
        files: ['dropdown-menu.tsx'],
        description: 'Action dropdown menu triggered by button',
        tags: ['dropdown-menu', 'menu', 'actions'],
    },
    resizable: {
        name: 'Resizable',
        category: 'layout',
        dependencies: ['react-resizable-panels', 'lucide-react'],
        files: ['resizable.tsx'],
        description: 'Resizable split panes and panel groups',
        tags: ['resizable', 'panels', 'split'],
    },
    'scroll-area': {
        name: 'ScrollArea',
        category: 'layout',
        dependencies: ['@radix-ui/react-scroll-area'],
        files: ['scroll-area.tsx'],
        description: 'Custom styled scrollbar area',
        tags: ['scroll-area', 'scrollbar', 'layout'],
    },
    collapsible: {
        name: 'Collapsible',
        category: 'layout',
        dependencies: ['@radix-ui/react-collapsible'],
        files: ['collapsible.tsx'],
        description: 'Interactive collapsible element',
        tags: ['collapsible', 'toggle', 'details'],
    },
    toggle: {
        name: 'Toggle',
        category: 'form',
        dependencies: ['@radix-ui/react-toggle', 'class-variance-authority'],
        files: ['toggle.tsx'],
        description: 'Two-state button that can be on or off',
        tags: ['toggle', 'button', 'switch'],
    },
    'toggle-group': {
        name: 'ToggleGroup',
        category: 'form',
        dependencies: ['@radix-ui/react-toggle-group', 'class-variance-authority'],
        files: ['toggle-group.tsx'],
        description: 'Group of two-state toggle buttons',
        tags: ['toggle-group', 'buttons', 'selection'],
    },

    // Media & Utility
    'aspect-ratio': {
        name: 'AspectRatio',
        category: 'media',
        dependencies: ['@radix-ui/react-aspect-ratio'],
        files: ['aspect-ratio.tsx'],
        description: 'Container with constrained aspect ratio',
        tags: ['aspect-ratio', 'media', 'container'],
    },
    calendar: {
        name: 'Calendar',
        category: 'form',
        dependencies: ['react-day-picker', 'lucide-react'],
        files: ['calendar.tsx'],
        description: 'Date picker calendar grid component',
        tags: ['calendar', 'date', 'picker'],
    },
    carousel: {
        name: 'Carousel',
        category: 'media',
        dependencies: ['embla-carousel-react', 'lucide-react'],
        files: ['carousel.tsx'],
        description: 'Fluid image and content carousel with swipe support',
        tags: ['carousel', 'slider', 'media'],
    },
    'error-boundary': {
        name: 'ErrorBoundary',
        category: 'feedback',
        dependencies: ['lucide-react'],
        files: ['error-boundary.tsx'],
        description: 'React error boundary component with fallback UI',
        tags: ['error-boundary', 'error', 'resilience'],
    },
    'language-switcher': {
        name: 'LanguageSwitcher',
        category: 'navigation',
        dependencies: ['react-i18next', 'lucide-react'],
        files: ['language-switcher.tsx'],
        description: 'Language selection dropdown for internationalization',
        tags: ['i18n', 'language', 'locale'],
    },
    'theme-customizer': {
        name: 'ThemeCustomizer',
        category: 'layout',
        dependencies: ['lucide-react', 'sonner'],
        files: ['theme-customizer.tsx'],
        description: 'Theme color and radius customization drawer',
        tags: ['theme', 'customizer', 'colors'],
    },
}

export const CATEGORIES = {
    form: 'Form Controls',
    'data-display': 'Data Display',
    feedback: 'Feedback',
    navigation: 'Navigation',
    overlay: 'Overlay',
    layout: 'Layout',
    media: 'Media',
}
